name: whitecodel_auto_link
description: A Dart package for automating the build, upload, and status check of APK using Diawi.
version: 1.0.7
repository: https://github.com/whitecodel/whitecodel_auto_link

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  whitecodel_auto_link: whitecodel_auto_link