name: whitecodel_auto_link
description: A Dart package for automating the build, upload, and get the link of the APK and IPA files.
version: 1.1.9
repository: https://github.com/whitecodel/whitecodel_auto_link

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  chalkdart: ^2.0.9
  dio: ^5.4.1
  interact: ^2.2.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  whitecodel_auto_link: whitecodel_auto_link